### ISSUE TITLE
TypeError: locations.data.forEach is not a function

### ISSUE THREAD

**Issue by ogillin** [kevinbungeneers/nhc-homekit#1]
I installed NPM and had to install node-gyp rebuild.

during last installation I had the following errors.

> mdns@2.3.3 install /usr/local/lib/node_modules/nhc-homekit/node_modules/mdns
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/ogillin/.node-gyp/7.5.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/nhc-homekit/node_modules/mdns/.node-gyp"
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

then when I start to run the system I had the below.
Do I need to have an active Apple developer account?
any suggestion?

og:Applications ogillin$ nhc-homekit
/usr/local/lib/node_modules/nhc-homekit/node_modules/nhc-client/lib/HomeControlClient.js:90
    locations.data.forEach(function(location) {
                   ^

TypeError: locations.data.forEach is not a function
    at JsonSocket.onMessage (/usr/local/lib/node_modules/nhc-homekit/node_modules/nhc-client/lib/HomeControlClient.js:90:20)
    at emitTwo (events.js:106:13)
    at JsonSocket.emit (events.js:192:7)
    at JsonSocket.onData (/usr/local/lib/node_modules/nhc-homekit/node_modules/nhc-client/lib/JsonSocket.js:42:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)

**Comment by ghost** [comment]
Hi, I have the same issue.

**Comment by kevinbungeneers** [comment]
Hi! i'm guessing this is because you don't have any locations configured with your NHC installation? I'm currently looking on how to solve this. I kinda assumed that when loading the available actions, each would belong to a certain location.

I'm closing this issue though, seeing it's coming from the nhc-client. See https://github.com/kevinbungeneers/nhc-client/issues/1
